This project Showcase EDA - Exploratory Data Analysis on the Austo Business Data

Business Context

Austo aims to understand customer preferences and the factors influencing car purchases in the US market. In order to be familiar with the types of cars preferred by the customers and factors influencing the car purchase behavior in the US market, Austo has contracted a consulting firm. Based on various market surveys, the consulting firm has created a dataset of 3 major types of cars that are extensively used across the US market. They have collected various details of the car owners which can be analyzed to understand the automobile market of the US. Austo's management team wants to understand the demand of the buyers and trends in the US market. They want to build customer profiles based on the analysis to identify new purchase opportunities so that they can manipulate the business strategy and production to meet certain demand levels. Further, the analysis will be a good way for management to understand the dynamics of a new market. Your task as a data scientist is to explore the dataset, uncover patterns, identify key variables, and derive insights that can guide business decisions.

Data Dictionary
* Age: Age of the customer
* Gender: Gender of the customer
* Profession: Indicates whether the customer is a salaried or business person
* Marital_status: Marital status of the customer
* Education: Refers to the highest level of education completed by the customer
* No_of_dependents: Number of dependents(partner/children/spouse) of the customer
* Personal_loan: Indicates whether the customer availed a personal loan or not
* House_loan: Indicates whether the customer availed house loan or not
* Partner_working: Indicates whether the customer's partner is working or not
* Salary: Annual Salary of the customer
* Partner_salary: Annual Salary of the customer's partner
* Total_salary: Annual household income (Salary + Partner_salary) of the customer's family
* Price: Price of the car
* Make: Car type (Hatchback/Sedan/SUV)

Business Requirements

1. Data Understanding & Cleaning
   - Inspect dataset shape, data types, and summary statistics
   - Identify and handle missing values
   - Detect and comment on outliers

2. Univariate Analysis
   - Analyze key numerical and categorical variables
   - Use appropriate visualizations (histograms, boxplots, count plots)

3. Bivariate Analysis
   - Explore relationships between key variables
   - Use scatter plots, bar plots, and correlation analysis

4. Insights & Interpretation
   - Summarize insights from your analysis
   - Clearly state business implications

GOAL -
Deliverable 
- A clean, well-documented Jupyter Notebook
- Clear visualizations with titles and interpretations

1. IMPORTING MODULES

In [ ]:
# <!-- IMPORTING MODULES  -->
from util.imports import * 

sns.set(style='whitegrid')

ModuleNotFoundError: No module named 'util'

:

2. LOADING DATASET: Austo automobile dataset

In [21]:
url = r'C:\Users\emman\Desktop\DATA_SCIENCE_ITC\MAY\DS_WK_1\DS_MAY_WK_1_ASSIGNMENT\data\austo_automobile 1.csv'
df = pd.read_csv(url)
df.head()

,Age,Gender,Profession,Marital_status,Education,No_of_Dependents,Personal_loan,House_loan,Partner_working,Salary,Partner_salary,Total_salary,Price,Make
0,24,Male,Salaried,Married,Post Graduate,4,No,Yes,Yes,52000,25000,77000,18000,Hatchback
1,28,Male,Salaried,Married,Post Graduate,3,No,Yes,No,68000,0,68000,18000,Hatchback
2,23,Male,Salaried,Married,Graduate,4,Yes,Yes,No,31000,0,31000,18000,Hatchback
3,26,Male,Business,Married,Post Graduate,4,Yes,Yes,Yes,66000,35000,101000,18000,Hatchback
4,28,Male,Business,Married,Post Graduate,4,Yes,No,No,64000,0,64000,18000,Hatchback

 3. Data Understanding & Cleaning

- Inspect dataset shape
- data types
- summary statistics

i. Inspect dataset shape

In [18]:
# Data Shape
df.shape

(1581, 14)

ii. data types

In [19]:
# Data types
df.dtypes

Age                  int64
Gender              object
Profession          object
Marital_status      object
Education           object
No_of_Dependents     int64
Personal_loan       object
House_loan          object
Partner_working     object
Salary               int64
Partner_salary       int64
Total_salary         int64
Price                int64
Make                object
dtype: object

iii. Summary statistics

In [20]:
# Data Summary statistics
df.describe

<bound method NDFrame.describe of       Age Gender Profession Marital_status      Education  No_of_Dependents  \
0      24   Male   Salaried        Married  Post Graduate                 4
1      28   Male   Salaried        Married  Post Graduate                 3
2      23   Male   Salaried        Married       Graduate                 4
3      26   Male   Business        Married  Post Graduate                 4
4      28   Male   Business        Married  Post Graduate                 4
...   ...    ...        ...            ...            ...               ...
1576   28   Male   Salaried        Married  Post Graduate                 2
1577   23   Male   Salaried         Single       Graduate                 2
1578   23   Male   Business        Married       Graduate                 4
1579   25   Male   Business        Married  Post Graduate                 3
1580   28   Male   Salaried        Married       Graduate                 4

     Personal_loan House_loan Partner_working  Salary  Partner_salary  \
0               No        Yes             Yes   52000           25000
1               No        Yes              No   68000               0
2              Yes        Yes              No   31000               0
3              Yes        Yes             Yes   66000           35000
4              Yes         No              No   64000               0
...            ...        ...             ...     ...             ...
1576           Yes         No              No   72000               0
1577           Yes        Yes              No   37000               0
1578           Yes        Yes             Yes   38000           28000
1579           Yes        Yes             Yes   58000           40000
1580            No        Yes             Yes   54000           40000

      Total_salary  Price       Make
0            77000  18000  Hatchback
1            68000  18000  Hatchback
2            31000  18000  Hatchback
3           101000  18000  Hatchback
4            64000  18000  Hatchback
...            ...    ...        ...
1576         72000  33000  Hatchback
1577         37000  33000  Hatchback
1578         66000  33000  Hatchback
1579         98000  33000  Hatchback
1580         94000  33000  Hatchback

[1581 rows x 14 columns]>

In [22]:
df.columns

Index(['Age', 'Gender', 'Profession', 'Marital_status', 'Education',
       'No_of_Dependents', 'Personal_loan', 'House_loan', 'Partner_working',
       'Salary', 'Partner_salary', 'Total_salary', 'Price', 'Make'],
      dtype='object')

In [23]:
df.info

<bound method DataFrame.info of       Age Gender Profession Marital_status      Education  No_of_Dependents  \
0      24   Male   Salaried        Married  Post Graduate                 4
1      28   Male   Salaried        Married  Post Graduate                 3
2      23   Male   Salaried        Married       Graduate                 4
3      26   Male   Business        Married  Post Graduate                 4
4      28   Male   Business        Married  Post Graduate                 4
...   ...    ...        ...            ...            ...               ...
1576   28   Male   Salaried        Married  Post Graduate                 2
1577   23   Male   Salaried         Single       Graduate                 2
1578   23   Male   Business        Married       Graduate                 4
1579   25   Male   Business        Married  Post Graduate                 3
1580   28   Male   Salaried        Married       Graduate                 4

     Personal_loan House_loan Partner_working  Salary  Partner_salary  \
0               No        Yes             Yes   52000           25000
1               No        Yes              No   68000               0
2              Yes        Yes              No   31000               0
3              Yes        Yes             Yes   66000           35000
4              Yes         No              No   64000               0
...            ...        ...             ...     ...             ...
1576           Yes         No              No   72000               0
1577           Yes        Yes              No   37000               0
1578           Yes        Yes             Yes   38000           28000
1579           Yes        Yes             Yes   58000           40000
1580            No        Yes             Yes   54000           40000

      Total_salary  Price       Make
0            77000  18000  Hatchback
1            68000  18000  Hatchback
2            31000  18000  Hatchback
3           101000  18000  Hatchback
4            64000  18000  Hatchback
...            ...    ...        ...
1576         72000  33000  Hatchback
1577         37000  33000  Hatchback
1578         66000  33000  Hatchback
1579         98000  33000  Hatchback
1580         94000  33000  Hatchback

[1581 rows x 14 columns]>

In [24]:
df.describe()

,Age,No_of_Dependents,Salary,Partner_salary,Total_salary,Price
count,1581.000000,1581.000000,1581.000000,1581.000000,1581.000000,1581.000000
mean,32.211259,2.457938,59732.447818,19720.430108,79452.877925,35597.722960
std,9.125477,0.943483,14278.642665,19480.214404,24855.936043,13633.636545
min,22.000000,0.000000,30000.000000,0.000000,30000.000000,18000.000000
25%,25.000000,2.000000,51000.000000,0.000000,61000.000000,25000.000000
50%,29.000000,2.000000,59000.000000,25000.000000,78000.000000,31000.000000
75%,38.000000,3.000000,71000.000000,38000.000000,96000.000000,47000.000000
max,60.000000,4.000000,90000.000000,80000.000000,158000.000000,70000.000000

In [28]:
df.groupby('Gender').value_counts()

Gender  Age  Profession  Marital_status  Education      No_of_Dependents  Personal_loan  House_loan  Partner_working  Salary  Partner_salary  Total_salary  Price  Make
Female  22   Salaried    Married         Graduate       3                 No             No          Yes              34000   28000           62000         31000  Hatchback    1
                                         Post Graduate  2                 No             No          Yes              52000   30000           82000         23000  Hatchback    1
                                                        4                 No             No          Yes              56000   32000           88000         28000  Hatchback    1
        23   Salaried    Married         Post Graduate  2                 Yes            No          Yes              59000   32000           91000         27000  Hatchback    1
        24   Salaried    Married         Graduate       2                 Yes            No          Yes              37000   40000           77000         32000  Hatchback    1
                                                                                                                                                                               ..
Male    60   Salaried    Married         Post Graduate  2                 No             No          No               81000   0               81000         63000  SUV          1
                                                        3                 No             No          No               83000   0               83000         57000  SUV          1
                                                                                                     Yes              79000   60000           139000        57000  SUV          1
                                                        4                 No             No          No               89000   0               89000         61000  SUV          1
                                                                          Yes            No          No               81000   0               81000         67000  SUV          1
Name: count, Length: 1581, dtype: int64

In [31]:
df.groupby(['Education','Gender'])['Price'].mean()

Education      Gender
Graduate       Female    48920.289855
               Male      31986.899563
Post Graduate  Female    46827.225131
               Male      32663.727960
Name: Price, dtype: float64

In [33]:
df.groupby(['Personal_loan'])['Price'].mean()

Personal_loan
No     36742.712294
Yes    34457.070707
Name: Price, dtype: float64